name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Generate requirements.txt
      run: |
        pip freeze > requirements.txt
    - name: Lint with flake8
      run: |
        flake8 practical2.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 practical2.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest  # Let pytest discover all the tests in the repository
    - name: Install cyclonedx-py
      run: |
        python -m pip install cyclonedx-py
    - name: Generate SBOM for practical2.py
      run: |
        cyclonedx-py requirements -r requirements.txt -o sbom_practical2.json
    - name: Upload SBOM as artifact
      uses: actions/upload-artifact@v3
      with:
        name: sbom-practical2
        path: sbom_practical2.json
